list: $/codeclutch/contact/models/message/columns.yaml
modelClass: Codeclutch\Contact\Models\Message
title: Messages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'codeclutch/contact/messages/update/:id'
